/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AuthConsentRouteImport } from './routes/_auth/consent'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as PaymentCheckoutRouteImport } from './routes/_payment/checkout'
import { Route as PaymentPricingRouteImport } from './routes/_payment/pricing'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as PublicRecallRouteImport } from './routes/_public/recall'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/_auth/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCheckoutRoute = PaymentCheckoutRouteImport.update({
  id: '/_payment/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPricingRoute = PaymentPricingRouteImport.update({
  id: '/_payment/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/_public/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRecallRoute = PublicRecallRouteImport.update({
  id: '/_public/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/consent': typeof AuthConsentRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/checkout': typeof PaymentCheckoutRoute
  '/pricing': typeof PaymentPricingRoute
  '/dashboard': typeof PublicDashboardRoute
  '/recall': typeof PublicRecallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/consent': typeof AuthConsentRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/checkout': typeof PaymentCheckoutRoute
  '/pricing': typeof PaymentPricingRoute
  '/dashboard': typeof PublicDashboardRoute
  '/recall': typeof PublicRecallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRoute
  '/_auth/consent': typeof AuthConsentRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_payment/checkout': typeof PaymentCheckoutRoute
  '/_payment/pricing': typeof PaymentPricingRoute
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/recall': typeof PublicRecallRoute
  '/api/chat': typeof ApiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/developer'
    | '/consent'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/checkout'
    | '/pricing'
    | '/dashboard'
    | '/recall'
    | '/api/chat'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/developer'
    | '/consent'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/checkout'
    | '/pricing'
    | '/dashboard'
    | '/recall'
    | '/api/chat'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/developer'
    | '/_auth/consent'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_payment/checkout'
    | '/_payment/pricing'
    | '/_public/dashboard'
    | '/_public/recall'
    | '/api/chat'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DeveloperRoute: typeof DeveloperRoute
  AuthConsentRoute: typeof AuthConsentRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PaymentCheckoutRoute: typeof PaymentCheckoutRoute
  PaymentPricingRoute: typeof PaymentPricingRoute
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicRecallRoute: typeof PublicRecallRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/consent': {
      id: '/_auth/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payment/checkout': {
      id: '/_payment/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payment/pricing': {
      id: '/_payment/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PaymentPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/recall': {
      id: '/_public/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof PublicRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DeveloperRoute: DeveloperRoute,
  AuthConsentRoute: AuthConsentRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  PaymentCheckoutRoute: PaymentCheckoutRoute,
  PaymentPricingRoute: PaymentPricingRoute,
  PublicDashboardRoute: PublicDashboardRoute,
  PublicRecallRoute: PublicRecallRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
